name: DMHandler CI

on:
  push:
    paths-ignore:
      - 'infrastructure/**'   # skip build if only infra changes
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build lcov

      - name: Install libcurl
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
      
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Configure CMake (Debug + Analysis)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: clang-tidy -p build $(find ./src ./include ./tests ./utility -name '*.cpp')

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --force \
            --std=c++17 \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --suppress=unmatchedSuppression \
            --suppress=toomanyconfigs \
            --suppress=unusedFunction:include/OrderSide.h \
            --suppress=unusedFunction:tests/tests_simulator.cpp \
            --suppress=unusedFunction:tests/tests_feed_handler.cpp \
            --suppress=unusedFunction:tests/tests_datasource_finnhubconnector.cpp \
            --suppress=unusedFunction:src/parser/MarketDataParserFactory.cpp \
            --suppress=unusedFunction:src/dataSource/FinnhubConnector.cpp \
            --suppress=unusedStructMember:tests/tests_parser.cpp \
            --suppress=*:third_party/crow/include/* \
            -I include \
            -I utility \
            -I third_party/crow/include \
            -I third_party/json/single_include \
            -i third_party/crow \
            -i third_party/asio \
            -i third_party/ixwebsocket \
            -i third_party/json/single_include \
            --suppress=missingInclude:include/parser/FinnhubMarketDataParser.h \
            ./include ./src ./tests ./utility
      
      - name: Configure CMake for Coverage
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Build with Coverage
        run: cmake --build build

      - name: Run Tests with CTest
        run: cd build && ctest --output-on-failure

      - name: Generate Code Coverage Report
        run: |
          lcov --directory build --capture --output-file coverage.info --ignore-errors mismatch
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/third_party/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage_report --ignore-errors mismatch

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/Testing/Temporary/LastTest.log

      - name: Upload Binary to S3
        if: success()
        run: |
          aws s3 cp build/DMHandler s3://dmhandler-build-artifacts/releases/DMHandler-v0.1.0-${{ github.sha }} \
            --metadata version=0.1.0,build=local
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Upload DMHandler Binary to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DMHandler
          path: build/DMHandler
